name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Change this to your main branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code source depuis le dépôt
    - name: Checkout repository
      uses: actions/checkout@v2

    # Installer Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.2'

    # Afficher la version de Flutter pour confirmation
    - name: Flutter Version
      run: flutter --version

    - name: Flutter Pub Get
      run: flutter pub get

    # Construire l'application Flutter pour le Web
    - name: Build Flutter Web
      run: flutter build web --release

    # Déployer sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web

name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'

      - name: Flutter Version
        run: flutter --version

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Download Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          # user_name: 'github-ci[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: 'Publish to gh-pages'