name: Flutter CI/CD

on:
  push:
    branches:
      - main  # Vous pouvez changer la branche ici
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout source code
      uses: actions/checkout@v3

    # Set up Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # Spécifiez une version ou utilisez 'stable'

    # Run Flutter Pub Get
    - name: Install dependencies
      run: flutter pub get

    # Run Tests
    - name: Run tests
      run: flutter test

    # Build Web App
    - name: Build Flutter Web
      run: flutter build web

    # Upload Web build artifacts (optional step if you want to use artifacts)
    - name: Upload web build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web/
