name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.18.6'

#    - name: Ensure Flutter channel stable
#      run: flutter channel stable

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Flutter Clean
      run: flutter clean

    - name: Run Flutter Tests
      run: flutter test
